## Job0

In [1]:
class Personne(object):
    
    def __init__(self, nom, prenom):
        self._nom = nom
        self._prenom = prenom

    def set_noms(self, nom, prenom):
        self._nom = nom
        self._prenom = prenom
        
 
    def get_noms(self):
        return  self._nom, self._prenom
        
    
    def SePresenter(self):
        print("Mon nom est", self._nom, "et mon prénom est", self._prenom)
        
P1= Personne("Mendizabal", "Emma")
print("prenom : ",P1.get_noms)
P1.SePresenter()



print (P1.get_noms())
P1.set_noms('Mendizabal','Manon')
print (P1.get_noms())
P1.SePresenter()

P2= Personne("Haidan", "Victor")
P2.SePresenter()     


prenom :  <bound method Personne.get_noms of <__main__.Personne object at 0x0000021166477D00>>
Mon nom est Mendizabal et mon prénom est Emma
('Mendizabal', 'Emma')
('Mendizabal', 'Manon')
Mon nom est Mendizabal et mon prénom est Manon
Mon nom est Haidan et mon prénom est Victor


# Question 
comment faire constructeurs par défaut et paramétrés? 

## Job1

In [2]:

class Personne(object):
    
    def __init__(self, nom, prénom):
        self.nom=nom
        self.prénom=prénom


class Livre(object):
    
    def __init__ (self, titre, nom_auteur, prénom_auteur):
        self.titre=titre
        self.nom_auteur=nom_auteur
        self.nom_auteur=prénom_auteur
        
    def set_livre(self, titre):
        self.titre=titre
        
    def get_livre(self):
        return self.titre
        
    def print(self):
        print(self.titre)

class Auteur(Personne):
    
    def __init__ (self, nom, prénom, oeuvre:list):
        self.oeuvre=oeuvre
        Personne.__init__(self, nom, prénom)
        
    def listerOeuvre(self):
        [print(l) for  l in self.oeuvre]
        
    def ecrireUnLivre(self, titre): 
        nouveau_livre=Livre(titre, self.nom, self.prénom)
        (self.oeuvre).append(titre)
        
    def get_oeuvre(self):
        return self.oeuvre
    
    def set_auteur(self, oeuvre):
        
        self.oeuvre=oeuvre
    

A1=Auteur("Victor","Hugo", ["Les Misérables"])
print(A1.oeuvre)
A1.ecrireUnLivre("abcd")
print(A1.oeuvre)
A1.listerOeuvre()
    
    

['Les Misérables']
['Les Misérables', 'abcd']
Les Misérables
abcd


## Job2

In [3]:
import numpy as np

class Client(Personne): 
    def __init__(self, nom, prénom, collection:list):
        self.collection=collection
        Personne.__init__(self, nom, prénom)
        
    def inventaire(self):
        [print(livreperso) for livreperso in self.collection]
        

class Bibliothèque(object):
    
    def __init__(self, nom, catalogue:list):
        self.nom=nom
        self.catalogue=catalogue
        
    def acheterLivre(self, nom_auteur, prénom_auteur, livre, quantité:int):
        if livre in (Auteur(nom, prénom, oeuvre).get_oeuvre): #on crée un Auteur ici non? 
            #Il faut faire un héritage, une agrégation? Ou une référence en ajoutant dans les attributs?
            (self.catalogue).append([Livre(livre, nom, prénom), quantité])
            print(self.catalogue)
        else:
            print("rupture de stock")
    
    def inventaire(self):
        [print(t_et_q) for t_et_q in self.catalogue]
        
    def louer(self, client:Client, livre): #dictionnaires = mieux
        for i in range(len(self.catalogue)):
            if livre in self.catalogue[i][0] and self.catalogue[i][1]>0: #pour avoir seulement les titres du catalogue, fonctionne?
                print("nombres de livres avant location:",self.catalogue[i][1])
                self.catalogue[i][1]-=1
                (client.collection).append(livre)
                
    def rendreLivres(self, client:Client):
        for livre in client.collection:
            if livre in list(zip(*self.catalogue))[0]:
                index_livre=list(zip(*self.catalogue))[0].index(livre)
                self.catalogue[index_livre][1]+=1
            else:
                self.catalogue.append([livre, 1])
            client.collection.remove(livre)
            print("livre:",livre, "collection:", client.collection, "catalogue :",self.catalogue)
            

        
C1=Client("Mendiz","Flo", ["premierlivredeflo","pythonpourlesnuls"])                
B1=Bibliothèque("bibli1", [['Les Misérables', 2],['passemiroir', 1]])
B1.louer(C1,'Les Misérables')
B1.rendreLivres(C1)


nombres de livres avant location: 2
livre: premierlivredeflo collection: ['pythonpourlesnuls', 'Les Misérables'] catalogue : [['Les Misérables', 1], ['passemiroir', 1], ['premierlivredeflo', 1]]
livre: Les Misérables collection: ['pythonpourlesnuls'] catalogue : [['Les Misérables', 2], ['passemiroir', 1], ['premierlivredeflo', 1]]


## Job7

In [ ]:
### class Player(Personne):
    
    def __init__ (self, color:str, nom, prénom):
        self.color=color
        Personne.__init__(self, nom, prénom)
        

class Board(object):
    
    def __init__(self, i, j):
        self.i=i
        self.j=j
        self.board=[['0']*self.j for x in range(self.i)]
        
    def play(self,column,color):
        line=self.i-1
        while self.board[line][column]!='0' and 0<=line: 
            line-=1
        if line>=0:
            self.board[line][column]=color
        else:
            return "chose an other column !"
        return self.board, line
           
    def print(self):
        print(self.board)   
        
        
    def gamePlay(self):
        end=False
        tour=0
        while not end:
            for player in ["J","R"]:
                column=int(input())
                print('joueur: ',player, ', et tour :',tour)
                board_state=self.play(column,player)
                print(board_state)
                if self.check_win(board_state[1], column,player):
                    return player, "win!"
               
            tour+=1
        return "lose"
 

    def check_win(self, line, column, player):
        if line+3<=self.i-1 and self.board[line+1][column]==player and self.board[line+2][column]==player and self.board[line+3][column]==player:
            return True
        elif column-3>=0 and self.board[line][column-3]==player and self.board[line][column-2]==player and self.board[line][column-1]==player and self.board[line][column]==player:
            return True
        elif column-2>=0 and column+1<=self.j-1 and self.board[line][column-2]==player and self.board[line][column-1]==player and self.board[line][column]==player and self.board[line][column+1]==player:
            return True
        elif column-1>=0 and column+2<=self.j-1 and self.board[line][column-1]==player and self.board[line][column]==player and self.board[line][column+1]==player and self.board[line][column+2]==player:
            return True
        elif column+3<=self.j-1 and self.board[line][column]==player and self.board[line][column+1]==player and self.board[line][column+2]==player and self.board[line][column+3]==player:
            return True

        


        
B1=Board(5,5)
# B1.play(2,"J")
B1.gamePlay()

## Job 20

In [ ]:
class AI_One(): 
    
    def __init__(self, color):
        self.color=color
        
    def column_not_full(self, column, plateau:Board):
        nb_columns=len(plateau.board[0])
        empty_columns=np.arange(nb_columns)
        for j in range (nb_columns):
            if plateau.board[0][j]!='0':
                np.delete(empty_columns,j)
        print(empty_columns)
        return empty_columns
    
    def think(self, plateau:Board):
        print(plateau.j)
        for column in range(plateau.j):
            line=plateau.i-1
            while plateau.board[line][column]!='0' and 0<=line:
                line-=1
            if plateau.check_win(line, column, self.color):
                plateau.play(column,self.color)
                return "win!", plateau.board, line
            else: 
                column=np.random.randint(0,len(plateau.board[0]))
                available_columns=self.column_not_full(column, plateau)
                if column not in available_columns:
                    column=available_columns[0]
                plateau.play(column,self.color)
                return "no perfect choice for AI for now: put on 1st column by default",plateau.board, line
       
    
    def GamePlayAgainstAI(self, plateau):
        end=False
        tour=0
        while not end:
            for player in ["J","R"]:
                if player==self.color:
                    print("joueur :",player)
                    AI_think=self.think(plateau)
                    print(np.array(plateau.board))
                    end=plateau.check_win(AI_think[2],column,player)
                    if end:
                        return player, "win!"
                else:
                    column=int(input())
                    print("joueur :", player)
                    board_state=plateau.play(column,player)
                    print(np.array(board_state[0]))
                    end=plateau.check_win(board_state[1], column,player)
                    if end:
                        return player, "win!"
                    
            tour+=1
        return "no one won"
  

AI1=AI_One('R')
B1=Board(5,5)
AI1.column_not_full(2,B1)
AI1.GamePlayAgainstAI(B1)


# Ne marche pas, car l'IA ne gagne pas même quand je lui en laisse l'occasion ... elle sait comment gagner mais pas comment faire perdre ... 

[0 1 2 3 4]


 2


joueur : J
[['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' 'J' '0' '0']]
joueur : R
5
[0 1 2 3 4]
[['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' 'J' 'R' '0']]


 4


joueur : J
[['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' 'J' 'R' 'J']]
joueur : R
5
[0 1 2 3 4]
[['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' '0']
 ['0' '0' '0' '0' 'R']
 ['0' '0' 'J' 'R' 'J']]


# 